* What is This?
  This repository is emacs config files. This config files is for me :p

* Requirement
  - Git

* How to Install
  1. clone this repository
     - git clone https://github.com/zkh001/dot-emacs.git ~/.emacs.d
  2. start Emacs 
     - start downloading packages. If stop due to an error which failure of installing packages when start first, you have to reboot the emacs!
     - reboot Emacs (optional / just in case)
  3. Enjoy!

* Memo
** [1] When the El-get is Bad State
 you MAY remove file el-get/.loaddefs.el* and el-get/.status.el*,
 if you notice that el-get, which is package-management tool, is
 bad behavior!

- rm ~/.emacs.d/el-get/.loaddefs.el*
- rm ~/.emacs.d/el-get/.status.el

** [2] When You Want to Kwow a Lot of Snippets
 The following tips is for yasnippets(snippets plugin)' snippets
 they support 
(REQUIREMENT: ruby, gem, rake)

- mkdir 
- cd ~/.emacs.d/snippets
- git clone --recursive https://github.com/capitaomorte/yasmate
- gem install plist trollop
- rake convert_bundles
